version: '3.7'

services:

  react:
    container_name: front_end
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 8001:8001
    environment:
      - CHOKIDAR_USEPOLLING=true




